### ISSUE TITLE
Runtime error with tsl2561 library

### ISSUE THREAD

**Issue by jhalpin100** [sim0nx/tsl2561#10]
Hi,

I just installed the tsl2561 library. The install appeared to be fine, but when I triy to run the following script:

#!/usr/bin/python
from tsl2561 import TSL2561
sensor = TSL2561()

I get

rpiw$ ./lux.py
Traceback (most recent call last):
  File "./lux.py", line 5, in <module>
    sensor = TSL2561()
  File "build/bdist.linux-armv6l/egg/tsl2561/tsl2561.py", line 65, in __init__
  File "build/bdist.linux-armv6l/egg/tsl2561/tsl2561.py", line 79, in _begin
  File "build/bdist.linux-armv6l/egg/tsl2561/tsl2561.py", line 129, in set_integration_time
  File "build/bdist.linux-armv6l/egg/tsl2561/tsl2561.py", line 88, in enable
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 114, in write8
  File "build/bdist.linux-armv6l/egg/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
IOError: [Errno 121] Remote I/O error

Any chance you see what's wrong? I'm running this on a raspberry pi with 

rpiw$ uname -a
Linux rpiw 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux

Apologies if this is the wrong place to bring this up, but I couldn't find a forum.

**Comment by sim0nx** [comment]
Hi,

Opening an issue on github is totally fine. There is no forum indeed.

The error you are experiencing does not come from the TSL library but from smbus.
My guess would be that there is an issue with the wiring or other hardware related issue.
The smbus library seems to be unable to talk to the device.

Sorry I couldn't help more.
