### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by c3rberus** [sim0nx/tsl2561#2]
When I run the provided example on my raspberry pi 3..

`from tsl2561 import TSL2561
if __name__ == "__main__":
  tsl = TSL2561(debug=1)
  print tsl.lux()`

I get this error...
root@stark:/home/pi# python tsl.py
Traceback (most recent call last):
  File "tsl.py", line 4, in <module>
    tsl = TSL2561(debug=1)
  File "build/bdist.linux-armv7l/egg/tsl2561/tsl2561.py", line 50, in **init**
  File "build/bdist.linux-armv7l/egg/tsl2561/tsl2561.py", line 57, in _begin
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 148, in readU8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 155, in read_byte_data
IOError: [Errno 5] Input/output error

Any ideas? I have I2C enabled.

root@stark:/home/pi# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by c3rberus** [comment]
User error, I didn't have the sensor wired correctly.
